### ISSUE TITLE
How to use android & iOS?

### ISSUE THREAD

**Issue by VinAppFun** [kanjirz50/viet-morphological-analysis-svm#1]
Hello! I'm developing applications on android and iOS (swift). Can you help me convert to java or swift langauge? Thanks ^^

**Comment by kanjirz50** [comment]
Hello!

I think there are 2 ways for running on android and iOS (Java or swift).

First:
This system requires SVM framework such as YamCha.
In Java language, libsvm or liblinear might work.
If you use libsvm or liblinear, you have to convert training data into libsvm formats.

Second:
Server machine runs as morphological analysis API server.
Android or iOS application access to server and get analyzed data.

**Comment by VinAppFun** [comment]
Thanks for replay! 
Second option can be a good way. 
Can you send to me the list of VNPos tags (N->Noun, V->Verb,SB->Symbol...)??
My Email: hienvinh24@gmail.com
Thanks

**Comment by kanjirz50** [comment]
VNPos archive contains VNPos tag list which are written in Vietnamese.
Pleae go to the [du-lieu-vnpos](http://vnlp.net/2009/06/25/corpus-vnpos/du-lieu-vnpos1/) and download du-lieu-vnpos and unzip.

You can find Tags.CHM in the archive.

**Comment by VinAppFun** [comment]
How to use it in NodeJS?
I want your project as API server but didn't run

**Comment by kanjirz50** [comment]
You can easily run the analyzer on API with bottle.

These are an example of how to make APIs.
- [https://www.toptal.com/bottle/building-a-rest-api-with-bottle-framework](https://www.toptal.com/bottle/building-a-rest-api-with-bottle-framework)
- [https://github.com/kanjirz50/web-nlp-interface/blob/master/app/controllers/sample.py](https://github.com/kanjirz50/web-nlp-interface/blob/master/app/controllers/sample.py)

Your Node JS application can send a GET or POST requests.
It's easy way to get a word segmented result.
