### ISSUE TITLE
I want to contact with you for some questions

### ISSUE THREAD

**Issue by huyhoang1990** [kanjirz50/viet-morphological-analysis-svm#2]
Hi Kanjirz,  Im from vietnam. I really interested in with your projects about nature language processing with vietnamese. 

Your demo link works well. But i cannot run it when follow your README.

Can you help me ?

**Comment by kanjirz50** [comment]
Hi huyhoang!
Thank you for you're interested in my project.

Which progress did you face on the problem?

**Comment by huyhoang1990** [comment]
:D, i have built successfully that user this project
https://github.com/kanjirz50/viet-morphological-analysis-svm

Thanks Kanji !

2016-09-09 11:00 GMT+07:00 Takahashi Kanji notifications@github.com:
