### ISSUE TITLE
Asking about train data

### ISSUE THREAD

**Issue by huyhoang1990** [kanjirz50/viet-morphological-analysis-svm#3]
Hi Kanjirz !
I tried to train data by following your README.

Step 1: I downloaded the corpus data (http://vnlp.net/2009/06/25/corpus-vnpos/)  and **concatenated all train files** (train1.txt.pos.pos, ..... train661.txt.pos.pos.pos) into one file was named is dataset.txt

Step 2: Converted dataset.txt to dataset.iob2 (cat dataset.txt | python ./utils/vnPOS_to_iob2.py > dataset.iob2)

Step 3: I run the command line (**make CORPUS=dataset.iob2 MODEL=./data/test/vnPOS FEATURE="F:-2..2:0..0 T:-2..-1" train**)

All steps worked well and generated the vnPos.model. Then i had used this model file and analyzed some sentences, but the result was not true, complete different from your file models.

Which step was wrong ? Can you help me to train data with sample corpus (http://vnlp.net/2009/06/25/corpus-vnpos/) ? 

I think Step 1 is not true :D 

Thanks !

**Comment by kanjirz50** [comment]
I found some error lines in vnPOS corpus.
I also found fatal error when running Yamcha.

I have fixed `utils/vnPOS_to_iob2.py` script.
Please pull the script and try again.
It may work.

Thanks!

**Comment by huyhoang1990** [comment]
Great, Its works well now 💃 . Thanks Kanjirz so much
